README.md file updated
dguzman-ort/BE-NT2-C-2023-I pull request #1
Opened 2023-03-22 01:04 UTC by MatiasMazzu

2023-03-22 01:31 UTC, dguzman-ort requested changes
hola @MatiasMazzu porfa agregale el `-`

ejemplo: 

`- Daniel Guzman, user`

2023-03-28 12:25 UTC, dguzman-ort reviewed
@MatiasMazzu quedo pendiente con este cambio.

2023-03-28 22:21 UTC, MatiasMazzu commented
@dguzman-ort listo, los cambios solicitados!

2023-03-29 02:22 UTC, dguzman-ort approved these changes

2023-03-29 02:22 UTC, merged